### ISSUE TITLE
目标计算机拒绝

### ISSUE THREAD

**Issue by WangLanxiao** [Maximilianxu/ServerManager#1]
感谢你的代码
我成功运行了前端 和 后端。
当我试图通过前端新建一个账户，遇到了这个错误。

pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。, Timeout: 30s, Topology Description: <TopologyDescription id: 60f01eff805b90cc3c86b719, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')>]>

期待你的回复

**Comment by Maximilianxu** [comment]
已线下解决。需要替换掉settings.js里的localhost为你实际服务器ip。
