### ISSUE TITLE
About the resources

### ISSUE THREAD

**Issue by theeagleofthedesert** [Maximilianxu/ServerManager#2]
Aside from the description of GPUs (which is 8 RTX3070), where can I find the description of other resources, e.g. CPU cores or memory ?

**Comment by Maximilianxu** [comment]
> Aside from the description of GPUs (which is 8 RTX3070), where can I find the description of other resources, e.g. CPU cores or memory ?

It does not support the management of CPU cores / memory. However, just treating them as GPUs will be OK. You could refer this link [a LXD tutorial on CPU management](https://ubuntu.com/blog/lxd-2-0-resource-control-412). Then you may put some functions in util.py to designate CPU cores for an instance, just like what we do for GPUs.
