### ISSUE TITLE
您好，请问一下这次更新和之前的版本有什么区别？

### ISSUE THREAD

**Issue by Hiram1026** [Maximilianxu/ServerManager#3]
谢谢！

**Comment by Maximilianxu** [comment]
1. 资源不够时，用户可以自己选择同其他人分享；
2. 可以分组控制配额，比如A组总共能申请m个GPU，B组共能申请n个GPU，相当于两种配额制并存，当然也可以只用一种策略；
3. 控制时长的update_left_time.py独立于server运行，参考start.sh，来避免多进程的bug；
4. 为了防止用户重复注册来绕过配额制，注册逻辑修改成只能允许固定的账户注册，参考settings.py里预定义的USER_NUMBER；
5. 重构了部分代码。

**Comment by Hiram1026** [comment]
谢谢，我部署时客户端network unavailable，你知道是什么原因吗？
![image](https://user-images.githubusercontent.com/86820620/161980854-5e3159f2-d9e8-47e7-9f63-8eadb9ae8ca6.png)
![image](https://user-images.githubusercontent.com/86820620/161980904-4a5c2aff-8bc1-4242-9451-8a24a9ac5723.png)
![image](https://user-images.githubusercontent.com/86820620/161980944-d4b34343-4ed1-41f0-8cff-0ec9fffe72f2.png)

**Comment by Maximilianxu** [comment]
可以无视。在局域网内不用管。

**Comment by Hiram1026** [comment]
![image](https://user-images.githubusercontent.com/86820620/161984382-7da866f6-f94b-45e5-a440-60466b592ce3.png)
实际就是没连上，我检查了服务端是OK的，JS客户端不行

**Comment by Maximilianxu** [comment]
你把settings.js里的ip改成你服务器实际IP试试，不要用127（新的readme提到了这个设置）。如果还不行，你可以看一下是不是有特殊的防火墙设置，如果有的话就sudo ufw allow 5000，sudo ufw allow 5000/tcp。

**Comment by Hiram1026** [comment]
还是不行，服务端和客户端还有没有其他需要修改的配置

**Comment by Hiram1026** [comment]
对了 我的client在yarn install的时候报了一些错误，

**Comment by Hiram1026** [comment]
![image](https://user-images.githubusercontent.com/86820620/161989905-00103c52-aa32-40e8-8ef9-b62fd5a99ae0.png)
yarn时遇到这个错误，我用了yarn install --update-checksums

**Comment by Maximilianxu** [comment]
参考 https://github.com/yarnpkg/yarn/issues/7584#issuecomment-536437423。
```
# edit ~/.yarnrc
unsafe-disable-integrity-migration false
# then run
yarn cache clean
yarn install -f
```
之前的版本需要修改settings.js的ip和注释掉app.py里的规则；新的版本只需要修改一下settings.js和app.py里的ip。
另外，server跑的时候最好是root环境，而不是sudo python...，应该先su root再python3...。

**Comment by Maximilianxu** [comment]
@Hiram1026 另外，我的yarn版本是1.22.5.

**Comment by Hiram1026** [comment]
![image](https://user-images.githubusercontent.com/86820620/162046060-210a259d-d0e5-492f-a5a7-6aa3e4d27a26.png)
版本都跟你一样了，现在又遇到了这样的问题，请问你知道原因吗

**Comment by Hiram1026** [comment]
![image](https://user-images.githubusercontent.com/86820620/162047799-6fc003d7-b714-4252-a1a3-7341df6007af.png)
版本跟您一致后，还是有这样的错误，参考yarn的issue也无法解决，emo

**Comment by Hiram1026** [comment]
![image](https://user-images.githubusercontent.com/86820620/162051531-f752f576-be42-4cf7-a2c2-8ac4ed42be03.png)
我装完一个它提示的版本，又会报错需要更高版本，请问你的node版本是多少

**Comment by Hiram1026** [comment]
多次尝试后用了node 14.0，感觉应该是安装成功了，但是又出现了下面的问题，附上yarn install的图和跑起来后的图
![image](https://user-images.githubusercontent.com/86820620/162053792-c9e2f7b5-648d-4a7d-b167-d0af5d83a1c1.png)
![image](https://user-images.githubusercontent.com/86820620/162053871-2b7f9bf8-5732-486e-aab7-1ce7ced78033.png)

**Comment by Hiram1026** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/data_1.8T/node-v14.14.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'yarn=1.22.5'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.14.0
4 verbose npm-session 2cb02ee504805960
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 timing stage:rollbackFailedOptional Completed in 2ms
8 timing stage:runTopLevelLifecycles Completed in 5ms
9 verbose stack Error: Invalid tag name "yarn=1.22.5": Tags may not have any characters that encodeURIComponent encodes.
9 verbose stack     at invalidTagName (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:91:15)
9 verbose stack     at fromRegistry (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:296:13)
9 verbose stack     at resolve (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:81:12)
9 verbose stack     at npa (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:52:10)
9 verbose stack     at /data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/lib/install/deps.js:231:14
9 verbose stack     at /data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at /data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at asyncMap (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
9 verbose stack     at exports.getAllMetadata (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/lib/install/deps.js:228:3)
9 verbose stack     at Installer.loadArgMetadata (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/lib/install.js:366:3)
9 verbose stack     at Installer.readGlobalPackageData (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/lib/install.js:667:8)
9 verbose stack     at Array.<anonymous> (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
9 verbose stack     at LOOP (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
9 verbose stack     at chain (/data_1.8T/node-v14.14.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
10 verbose cwd /data_1.8T/ServerManager
11 verbose Linux 4.15.0-142-generic
12 verbose argv "/data_1.8T/node-v14.14.0-linux-x64/bin/node" "/usr/local/bin/npm" "install" "--global" "yarn=1.22.5"
13 verbose node v14.14.0
14 verbose npm  v6.14.8
15 error code EINVALIDTAGNAME
16 error Invalid tag name "yarn=1.22.5": Tags may not have any characters that encodeURIComponent encodes.
17 verbose exit [ 1, true ]

**Comment by Maximilianxu** [comment]
1. network unavailable不是问题，我这里也是这个输出
2. npm 安装某个确定版本是 npm install --global yarn@1.22.5，不是 =
3. 我的node版本 node v14.17.0，npm版本 6.14.13
4. 你本地浏览器报network error，可以用chrome按F12，把错误信息发我(console和network页)，服务端如果有输出也发一下，不要用nohup + &，直接su root && python3 app.py
5. 如果可以，把sudo ufw status的输出发一下。
![image](https://user-images.githubusercontent.com/14119191/162105601-dfd851bc-9b33-4bb1-ba4f-78c222b7871b.png)

**Comment by Maximilianxu** [comment]
@Hiram1026  我的注册+尝试登录的console输出：
![image](https://user-images.githubusercontent.com/14119191/162105198-0e943c2e-8a23-4c86-9549-d4a3b61ff56f.png)
![image](https://user-images.githubusercontent.com/14119191/162105204-fbe54d1b-5c36-4775-a50f-d2235bc5aca8.png)
network输出
![image](https://user-images.githubusercontent.com/14119191/162105236-8d6a2680-950d-4dfe-9fe8-a1787c5dd354.png)

**Comment by Hiram1026** [comment]
好的 麻烦您再帮我看下
![image](https://user-images.githubusercontent.com/86820620/162136866-cd3a0abe-6ccf-45c1-a45b-fd9e70708562.png)
![image](https://user-images.githubusercontent.com/86820620/162137297-77336231-b317-420c-a9b8-53f6268cce4b.png)
![image](https://user-images.githubusercontent.com/86820620/162137443-c8a23700-63bd-468a-b815-ab7c7b12a3e3.png)
服务端没有收到任何请求

**Comment by Maximilianxu** [comment]
这样看来客户端发了请求，服务端没收到，有可能中间被block了。
1. 提供sudo netstat -tulpn | grep 5000的输出
2. 提供sudo ufw status的输出
3. 另外，sudo tcpdump -i eno2 -s 1500 port 5000可以监测网络，把eno2换成你的网卡，看一下是否有输出。

**Comment by Hiram1026** [comment]
![image](https://user-images.githubusercontent.com/86820620/162145989-27d266ee-1f5e-46b8-b4ae-9043570e4c9f.png)
![image](https://user-images.githubusercontent.com/86820620/162146156-24ee34f3-b7f8-420b-b75b-357a71c6e29e.png)
![image](https://user-images.githubusercontent.com/86820620/162146541-7c69cf1b-d927-4cf1-b839-5e6b3b159427.png)
另外我在另一台服务器上同样的配置试过了，也是相同的问题。您看方便加一下WX吗，我是电子科技大学的。

**Comment by Maximilianxu** [comment]
17763200154。你加一下我吧。我大概知道咋回事了。

**Comment by Maximilianxu** [comment]
多网卡导致的bug，需要在app.py里app.run(host='xxx', port=5000)显式提供ip。
